#!/bin/bash
url=$1
banner (){
    clear
    echo " =============== MEDIA DOWNLOAD ==============="
    echo -e "\e[1m\e[32m ______  ___  ___ _    _ .   _   ___   _  _ _ _"
    echo "   ||   |__/ |___  \  /  |  /_\  |__    \/  |/ "
    echo "   ||   |  \ |___   \/   | /   \  __|  _/\_ |\_"
    echo -e "\e[0m\e[39m ______________________________________________"
    echo " REDES SOCIAIS:                       treviasxk"
    echo " VERSÃO:                              1.0.1.0"
    echo " LICENÇA:                             GPL-3.0"
    echo " =============================================="
}

menu (){
    echo -e "URL: \e[1m\e[32m$url\e[0m\e[39m"
    echo " 1 - Vídeo Original"
    echo " 2 - Vídeo 1080p"
    echo " 3 - Vídeo 720p"
    echo " 4 - Vídeo 480p"
    echo " 5 - Vídeo 360p"
    echo " 6 - Audio 128kb"
    echo " 7 - Baixar atualizações"
    echo " 8 - Sair"
    read CHOICE
    banner
    case $CHOICE in
        1)
            echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m INICIANDO PROCESSO... \e[0m"
            youtube-dlc -o "/storage/emulated/0/Movies/%(title)s.%(ext)s" $url
            echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m FINALIZADO! \e[0m"
        ;;
        2)
            echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m INICIANDO PROCESSO... \e[0m"
            youtube-dlc -o "/storage/emulated/0/Movies/%(title)s.%(ext)s" $url 'best[height<=1080p]'
            echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m FINALIZADO! \e[0m"
        ;;
        3)
            echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m INICIANDO PROCESSO... \e[0m"
            youtube-dlc -o "/storage/emulated/0/Movies/%(title)s.%(ext)s" $url 'best[height<=720p]'
            echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m FINALIZADO! \e[0m"
        ;;
        4)
            echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m INICIANDO PROCESSO... \e[0m"
            youtube-dlc -o "/storage/emulated/0/Movies/%(title)s.%(ext)s" $url 'best[height<=480p]'
            echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m FINALIZADO! \e[0m"
        ;;
        5)
            echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m INICIANDO PROCESSO... \e[0m"
            youtube-dlc -o "/storage/emulated/0/Movies/%(title)s.%(ext)s" $url 'best[height<=360p]'
            echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m FINALIZADO! \e[0m"
        ;;
        6)
            echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m INICIANDO PROCESSO... \e[0m"
            youtube-dlc --extract-audio --audio-format mp3 -o "/storage/emulated/0/Music/%(title)s.%(ext)s" $url
            echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m FINALIZADO! \e[0m"
        ;;
        7)
            echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m ATUALIZANDO... \e[0m"
            curl -s -L https://raw.githubusercontent.com/treviasxk/media-download/main/install.sh -o $HOME/install
            chmod +x $HOME/install
            sleep 1
            bash $HOME/install
        ;;
        8)
            clear
            exit
        ;;
        *)
            echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m Selecione uma opção válido! \e[0m"
            menu
        ;;
    esac
}

banner
menu